CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'member',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS project (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  owner_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT NOT NULL,
  requirement TEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  auto_mode TINYINT NOT NULL DEFAULT 0,
  current_node VARCHAR(32),
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS task_event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL,
  seq INT NOT NULL,
  event VARCHAR(32) NOT NULL,
  agent VARCHAR(32),
  data TEXT,
  ts BIGINT,
  CONSTRAINT uk_task_seq UNIQUE (task_id, seq));

CREATE TABLE IF NOT EXISTS artifact (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(32) NOT NULL,
  path VARCHAR(500) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS llm_model (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  litellm_model_name VARCHAR(128) NOT NULL,
  api_key_enc VARCHAR(500),
  enabled TINYINT NOT NULL DEFAULT 1);

CREATE TABLE IF NOT EXISTS agent_role_config (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(32) NOT NULL UNIQUE,
  system_prompt TEXT,
  default_model_id BIGINT);
